# Generated by Django 4.2.7 on 2024-01-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
